version: "3.9"
services:
 web:
  container_name: web
  build: .
  ports:
   - "80:80"
  volumes:
   - ./www:/var/www/html
  depends_on:
   - mysql
   - cache
  environment:
   DOCKER_PMA_HOST: mysql
   DOCKER_PMA_USER: 'root'
   DOCKER_PMA_PASSWORD: '1q2w3e4r5t'
   DOCKER_PMA_PORT: "3306"
  links:
   - mysql
 mysql:
  container_name: mysql
  image: mysql:5.7
  restart: always
  environment: 
   MYSQL_DATABASE: 'homestead'
   MYSQL_USER: 'homestead'
   MYSQL_PASSWORD: 'secret'
   MYSQL_ROOT_PASSWORD: '1q2w3e4r5t'
  ports:
   - "3306:3306"
  volumes:
   - ./databases/:/var/lib/mysql
 cache:
  container_name: cache_server
  image: redis:6.2-alpine
  restart: always
  ports:
    - '6379:6379'
  command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  volumes: 
    - cache:/data
volumes:
  cache:
    driver: local